Jenkinsfile (Declarative Pipeline)
pipeline {
    agent { docker { image 'maven3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
				sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}

